### ISSUE TITLE
html and image in a subfolder 

### ISSUE THREAD

**Issue by carobarreirov** [MikeCHackett/MikeCHackett.github.io#1]
You can move out for the subfolder the html and image for it to show in the github.io page. 
Also, I am noticing you have not changed the image name and extension in your html tag <image> 
@MikeCHackett

**Comment by MikeCHackett** [comment]
I have the html file and the image inside the folder that is uploaded to github and I uploaded the image and the html file to github as well but I still can't see anything on the website.
I changed the image name but I don't know if you want me to change my html index name too?
________________________________
From: Caro Barreiro ***@***.***>
Sent: Monday, July 12, 2021 2:05 AM
To: MikeCHackett/MikeCHackett.github.io ***@***.***>
Cc: MikeCHackett ***@***.***>; Mention ***@***.***>
Subject: [MikeCHackett/MikeCHackett.github.io] html and image in a subfolder (#1)


You can move out for the subfolder the html and image for it to show in the github.io page.
Also, I am noticing you have not changed the image name and extension in your html tag [X]
@MikeCHackett<https://github.com/MikeCHackett>

**Comment by MikeCHackett** [comment]
Nevermind I just gave it some time to load and the website is working now. Thank you so much for your help.
________________________________
From: Caro Barreiro ***@***.***>
Sent: Monday, July 12, 2021 2:05 AM
To: MikeCHackett/MikeCHackett.github.io ***@***.***>
Cc: MikeCHackett ***@***.***>; Mention ***@***.***>
Subject: [MikeCHackett/MikeCHackett.github.io] html and image in a subfolder (#1)


You can move out for the subfolder the html and image for it to show in the github.io page.
Also, I am noticing you have not changed the image name and extension in your html tag [X]
@MikeCHackett<https://github.com/MikeCHackett>
